services:
  epaper-nas-display:
    image: ${EPAPER_IMAGE:-ghcr.io/ccawmiku/epaper-nas-display:0.1.3}
    container_name: epaper-nas-display
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "15001:15001"
      - "15002:15001"
