services:
  epaper-nas-display:
    image: ${EPAPER_IMAGE:-ghcr.io/ccawmiku/epaper-nas-display:0.1.7}
    container_name: epaper-nas-display
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "15001:15001"
      - "15002:15001"
      - "15002:15002/udp"
    # 若在 NAS 环境中 Docker 无法直接穿透 UDP 广播至局域网，建议启用 host 网络模式：
    # network_mode: host
